Add sync option support to HTTP2StreamChannel
apple/swift-nio-http2 pull request #282
Opened 2021-03-15 11:11 UTC by glbrntt

Motivation:

SwiftNIO 2.27.0 added support for synchronous channel options allowing
callers to get options synchronously -- saving a future allocation -- if
they know they're on the correct event loop. 'HTTP2StreamChannel' should
support this.

Modifications:

- Add 'HTTP2StreamChannel.SynchronousOptions' with conformance to
  'NIOSynchronousChannelOptions'

Result:

Callers can get and set options synchronously on 'HTTP2StreamChannel'

2021-03-15 11:22 UTC, Lukasa approved these changes
LGTM! Want to follow-up with a separate patch to _use_ the sync options API on the underlying channel to get at the autoRead channel option when it's available?

2021-03-15 11:22 UTC, Lukasa commented on Sources/NIOHTTP2/HTTP2StreamChannel.swift
> +        self.eventLoop.assertInEventLoop()
As these are now called publicly through APIs where the user is required to get them correct, I think we should lift these up to preconditions.

2021-03-15 11:22 UTC, Lukasa requested changes
Sorry, per earlier note I do have feedback here.

2021-03-15 13:59 UTC, glbrntt commented
All the CI -- except for the nightly job, which is expected to fail -- run without failures until they hit an issue reporting the status.

2021-03-15 14:53 UTC, Lukasa requested changes

2021-03-15 14:53 UTC, Lukasa commented on Sources/NIOHTTP2/HTTP2StreamChannel.swift
> +    public struct SynchronousOptions: NIOSynchronousChannelOptions {
Does this struct need to be `public`?

2021-03-15 14:53 UTC, Lukasa commented on Sources/NIOHTTP2/HTTP2StreamChannel.swift
> +        @inlinable
We can remove the `inlinable` on these two, we can't inline through this.

2021-03-15 14:53 UTC, Lukasa commented on Sources/NIOHTTP2/HTTP2StreamChannel.swift
> +    public final var syncOptions: NIOSynchronousChannelOptions? {
`HTTP2StreamChannel` is a `final` class so we don't need `final` here.

2021-03-15 15:16 UTC, Lukasa approved these changes

2021-03-16 07:39 UTC, Lukasa commented
@swift-nio-bot test this please

2021-03-16 08:38 UTC, Lukasa commented
Merging over the nightly failure.

2021-03-16 08:38 UTC, merged