Optimise reading of contiguous integers
apple/swift-nio-http2 pull request #312
Opened 2021-11-24 15:53 UTC by lmcd

I noticed this optimisation merged into `swift-nio` a few days ago: https://github.com/apple/swift-nio/pull/1987 by @weissi 
This PR applies this new read method to a few instances in `HTTP2FrameParser` when contiguous integers were being read from a `ByteBuffer`

2021-11-24 15:56 UTC, Lukasa requested changes
Thanks for this, it generally looks great! I've left a few notes in the diff. Sadly, we can't merge this until we tag a new NIO release, and then we'll need to update this patch to require that NIO version.

2021-11-24 15:56 UTC, Lukasa commented on Sources/NIOHTTP2/HTTP2FrameParser.swift
> +            let values = bytes.readMultipleIntegers(as: (UInt32, UInt8).self)!
This can be cleaned up as:

```suggestion
            let (raw, weight) = bytes.readMultipleIntegers(as: (UInt32, UInt8).self)!
```

2021-11-24 15:56 UTC, Lukasa commented on Sources/NIOHTTP2/HTTP2FrameParser.swift
> +        let values = bytes.readMultipleIntegers(as: (UInt32, UInt8).self)!
Same here.

2021-11-24 15:56 UTC, Lukasa commented on Sources/NIOHTTP2/HTTP2FrameParser.swift
> +            let values = bytes.readMultipleIntegers(as: (UInt16, UInt32).self)!
This can be cleaned up as:

```suggestion
            let (rawIdentifier, value) = bytes.readMultipleIntegers(as: (UInt16, UInt32).self)!
```

2021-11-24 15:56 UTC, Lukasa commented on Sources/NIOHTTP2/HTTP2FrameParser.swift
> +        let values = bytes.readMultipleIntegers(as: (UInt32, UInt32).self)!
Same cleanup can be done here.

2021-11-24 15:56 UTC, Lukasa commented on Sources/NIOHTTP2/HTTP2FrameParser.swift
> +        guard let values = self.readMultipleIntegers(as: (UInt16, UInt8, UInt8, UInt8, UInt32).self) else {
And the same cleanup can be done with this conditional binding too.

2021-11-24 16:09 UTC, lmcd commented
@Lukasa - I've made those changes. I've left the first one (inside the `guard`) as it's debatable which approach is better for clarity, but I can change that too if you like.

Also added another commit that does the same for writes.

2021-11-26 09:35 UTC, Lukasa requested changes
Great, if you can update Package.swift to lift the lower NIO version bound to the newly-released 2.35.0 we should be able to merge this.

2022-01-19 12:10 UTC, weissi commented
friendly ping @lmcd

2022-05-17 09:43 UTC, closed without merging