Implement RFC8441 Extended CONNECT
apple/swift-nio-http2 pull request #441
Opened 2024-06-20 16:03 UTC by ehaydenr

addresses #92

2024-06-20 16:04 UTC, Lukasa commented
@swift-server-bot add to allowlist

2024-06-20 16:12 UTC, Lukasa commented on Sources/NIOHTTP2/ConnectionStateMachine/HasExtendedConnectSettings.swift
> +// Copyright (c) 2017-2024 Apple Inc. and the SwiftNIO project authors
```suggestion
// Copyright (c) 2024 Apple Inc. and the SwiftNIO project authors
```

2024-06-20 16:13 UTC, Lukasa commented on Sources/NIOHTTP2/ConnectionStateMachine/HasExtendedConnectSettings.swift
> +// Copyright (c) 2017-2024 Apple Inc. and the SwiftNIO project authors
Also, you'll need to update this line:

https://github.com/apple/swift-nio-http2/blob/8d8eb609929aee75336a0a3d2417280786265868/scripts/soundness.sh#L21

It needs to become:

```
sed -e 's/20[12][7890123]-20[12][8901234]/YEARS/' -e 's/20[12][8901234]/YEARS/' 
```

2024-06-21 08:06 UTC, glbrntt requested changes
I left a couple of nits but otherwise this looks really good!

2024-06-21 08:52 UTC, Lukasa commented on Sources/NIOHTTP2/HTTP2Error.swift
> +        private var storage: StringAndLocationStorage
That's probably true, but on the other hand maybe we should just schedule a task to fix them all in one go.

2024-06-21 09:58 UTC, glbrntt commented on Sources/NIOHTTP2/HTTP2Error.swift
> +        private var storage: StringAndLocationStorage
Okay. Let's leave this one as is and sort them all out separately.

2024-06-21 16:24 UTC, glbrntt approved these changes
Nice patch, thanks @ehaydenr!

2024-06-24 07:33 UTC, merged